server:
  port: 9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
spring:
  profiles:
    active: dev
  application:
    name: employee-leave-service

#  jackson:
#    serialization:
#      fail-on-self-references: true