server:
  port: 9200
spring:
  profiles:
    active: dev
  application:
    name: employee-management-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

service:
  url:
    login: employee-login-service

