server:
  port: 9400
spring:
  profiles:
    active: dev
  application:
    name: employee-validation-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
service:
  url:
    login: employee-validation-service
